version: "3"

services:

  db:
    image: ${DB_IMAGE}
    container_name: ada_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - vlm_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: always

  app:
    build: ..
    restart: always
    container_name: ada_app
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      TG_TOKEN: ${TG_TOKEN}

volumes:
  vlm_db:
